### ISSUE TITLE
How to decryp it?

### ISSUE THREAD

**Issue by guranu** [ogniK5377/RPGMakerXpCustomContainer#4]
What if (for exmple) i want it to decrypt this custom container how do i do that??

**Comment by ogniK5377** [comment]
Hi! Ultimately it depends if a custom key is used or not for the custom container. If the person who uses the custom container has packed their game archive with a custom key, you'll need to find a suitable decrypter which allows you to input your own key. 

This project does not contain a decrypter. This project mainly aims to patch the archive loading routines in RPG Maker XP to allow for a non-hardcoded key

If you're looking to encrypt your files with a custom key you can look at: https://github.com/ogniK5377/RPGMakerXpEncryptor
However it does not provide a method for decrypting the archive! Hope this is of some use :)
